In [3]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [6]:
x * 2

array([2., 4., 6.])

In [7]:
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
x.shape

(2, 3)

In [9]:
x + y

array([[ 3.,  6.,  9.],
       [ 6.,  9., 12.]])

In [11]:
x = x.flatten()
x

array([1., 2., 3., 4., 5., 6.])

In [12]:
x[np.array([0, 2, 4])]

array([1., 3., 5.])

In [14]:
x[x > 3]

array([4., 5., 6.])